# Generated by Django 2.0.5 on 2018-06-01 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.IntegerField()),
            ],
            options={
                'db_table': 'exeat',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'slot',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('isadmin', models.BooleanField()),
                ('email', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tutor',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='tutor',
            field=models.ForeignKey(db_column='tutor', on_delete=django.db.models.deletion.PROTECT, to='exeatsapp.Tutor'),
        ),
        migrations.AddField(
            model_name='slot',
            name='allocatedto',
            field=models.ForeignKey(blank=True, db_column='allocatedto', null=True, on_delete=django.db.models.deletion.PROTECT, to='exeatsapp.Student'),
        ),
        migrations.AddField(
            model_name='slot',
            name='tutor',
            field=models.ForeignKey(db_column='tutor', on_delete=django.db.models.deletion.PROTECT, to='exeatsapp.Tutor'),
        ),
    ]
