# Generated by Django 2.0.6 on 2018-06-06 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exeatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='allocatedto',
            field=models.ForeignKey(blank=True, db_column='allocatedto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='exeatsapp.Student'),
        ),
    ]
