# Generated by Django 2.0.6 on 2018-11-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exeatsapp', '0002_auto_20180606_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='alert',
            field=models.BooleanField(default=False),
        ),
    ]
